
from .base import SPINE_CSV_FORMAT, DataHandler

exclude_filters = {
    "": []
}


class ScotHousingRegDataHandler(DataHandler):
    fileencoding='Latin-1'
    def all_filters(self, row: dict) -> bool:

        # other filters?
        for fieldname, exclude_values in exclude_filters.items():
            if row.get(fieldname) in exclude_values:
                return False
        return True
    def map_date(self, datestr):
        return super().map_date(datestr)

    def find_names(self, row:dict) -> list:
        ''' returns name keys which have non-null values'''
        # 
        name_keys=[]
        v = ['Social Landlord']

        for i in v:
            if row[i]: name_keys.append(i)
        return name_keys


    def format_row(self,namefield,row) -> dict:
        '''format a row into Spine format, for given namefield'''
        new_row={}
        for field in row:
            row[field] = row[field].strip()

        new_row["uid"] =  'GB-SHR-'+ row['Reg No']    # SHPE from FindThatCharity: social housing providers England
        new_row["organisationname"] = row[namefield]
        new_row["normalisedname"] = ''
        new_row["companyid"] = row['Reg No']     
        new_row["charitynumber"] = ''
        new_row["housenumber"] = ''
        
        new_row["addressline1"] = ''
        new_row["addressline2"] = ''
        new_row["addressline3"] = ''
        new_row["addressline4"] = ''
        new_row["addressline5"] = ''
        new_row["city"] = ''
        new_row["localauthority"] = ''
        new_row["postcode"] = ''
        new_row["source"] = 'ScottishHousingRegulator'
        new_row["dissolutiondate"] = '' 
        new_row["registrationdate"] = ''
        
        return new_row
        
    def transform_row(self, row: dict) -> list[dict]:
        '''returns list of rows in SPINE format'''
        #  check for multiple names
        name_keys = self.find_names(row)
        
        spine_rows = []
        for name in name_keys:
            spine_rows.append(self.format_row(name,row))

        return spine_rows


'''
Scottish Housing Register data fields

Financial Year,
Reg No,
Social Landlord,
Constitution,
Clients,
Landlord type,
Settlement,
National Operator,

SOCI - Turnover,SOCI - Operating costs,
SOCI - Gain/(loss) on disposal of property plant and equipment,
SOCI - Exceptional items,
SOCI - Operating surplus/(deficit),
SOCI - Share of operating surplus/(deficit) in joint ventures and as sociates,
SOCI - Interest receivable,
SOCI - Interest payable,
SOCI - Other financing (costs)/income,
SOCI - Release of negative goodwill,
SOCI - Movement in fair value of financial instruments,
SOCI - Decrease in valuation of housing properties,
SOCI - Reversal of previous decrease in valuation of housing properties,
SOCI - Total,
SOCI - Surplus/(deficit) before tax,
SOCI - Tax (payable)/recoverable,
SOCI - Surplus/(deficit) for the year,Unrealised surplus/(deficit) on revaluation of housing properties,
SOCI - Actuarial (loss)/gain in respect of pension schemes,
SOCI - Change in fair value of hedged financial instruments,
SOCI - Total comprehensive income for the year,
SOCE - Balance at end of the previous year - Share capital,
SOCE - Balance at end of the previous year - 'Revenue reserve Restricted fund,
SOCE - Balance at end of the previous year year - 'Revenue reserve Unrestricted fund,
SOCE - Balance at end of the previous year - Restricted reserve,
SOCE - Balance at end of the previous year - Revaluation reserve,
SOCE - Balance at end of the previous year - Total excluding non-controlling interest,
SOCE - Balance at end of the previous year - Non-controlling interest,
SOCE - Balance at end of the previous year - Total including non-controlling interest,
SOCE - Opening balance adjustments - Share capital,
SOCE - Opening balance adjustments - Revenue reserve Restricted fund,
SOCE - Opening balance adjustments - Revenue reserve Unrestricted fund,
SOCE - Opening balance adjustments - Restricted reserve,
SOCE - Opening balance adjustments - Revaluation reserve,
SOCE - Opening balance adjustments - Total excluding non-controlling interest,
SOCE - Opening balance adjustments - Non-controlling interest,
SOCE - Opening balance adjustments - Total including non-controlling interest,
SOCE - Issue of shares - Share capital,
SOCE - Issue of shares - Revenue reserve Restricted fund,
SOCE - Issue of shares - Revenue reserve Unrestricted fund,
SOCE - Issue of shares - Restricted reserve,
SOCE - Issue of shares - Revaluation reserve,
SOCE - Issue of shares - Total excluding non-controlling interest,
SOCE - Issue of shares - Non-controlling interest,
SOCE - Issue of shares - Total including non-controlling interest,
SOCE - Cancellation of shares - Share capital,
SOCE - Cancellation of shares - Revenue reserve Restricted fund,
SOCE - Cancellation of shares - Revenue reserve Unrestricted fund,
SOCE - Cancellation of shares - Restricted reserve,
SOCE - Cancellation of shares - Revaluation reserve,
SOCE - Cancellation of shares - Total excluding non-controlling interest,
SOCE - Cancellation of shares - Non-controlling interest,
SOCE - Cancellation of shares - Total including non-controlling interest,
SOCE - Surplus/(deficit) from statement of comprehensive income - Share capital,
SOCE - Surplus/(deficit) from statement of comprehensive income - Revenue reserve Restricted fund,
SOCE - Surplus/(deficit) from statement of comprehensive income - Revenue reserve Unrestricted fund,
SOCE - Surplus/(deficit) from statement of comprehensive income - Restricted reserve,
SOCE - Surplus/(deficit) from statement of comprehensive income - Revaluation reserve,
SOCE - Surplus/(deficit) from statement of comprehensive income - Total excluding non-controlling interest,
SOCE - Surplus/(deficit) from statement of comprehensive income - Non-controlling interest,
SOCE - Surplus/(deficit) from statement of comprehensive income - Total including non-controlling interest,
SOCE - Transfer from revaluation reserve to revenue reserve - Share capital,
SOCE - Transfer from revaluation reserve to revenue reserve - Revenue reserve Restricted fund,
SOCE - Transfer from revaluation reserve to revenue reserve - Revenue reserve Unrestricted fund,
SOCE - Transfer from revaluation reserve to revenue reserve - Restricted reserve,
SOCE - Transfer from revaluation reserve to revenue reserve - Revaluation reserve,
SOCE - Transfer from revaluation reserve to revenue reserve - Total excluding non-controlling interest,
SOCE - Transfer from revaluation reserve to revenue reserve - Non-controlling interest,
SOCE - Transfer from revaluation reserve to revenue reserve - Total including non-controlling interest,
SOCE - Transfer of restricted expenditure from unrestricted reserve - Share capital,
SOCE - Transfer of restricted expenditure from unrestricted reserve - Revenue reserve Restricted fund,
SOCE - Transfer of restricted expenditure from unrestricted reserve - 'Revenue reserve Unrestricted fund',
SOCE - Transfer of restricted expenditure from unrestricted reserve - Restricted reserve,
SOCE - Transfer of restricted expenditure from unrestricted reserve - Revaluation reserve,
SOCE - Transfer of restricted expenditure from unrestricted reserve - Total excluding non-controlling interest,
SOCE - Transfer of restricted expenditure from unrestricted reserve - Non-controlling interest,
SOCE - Transfer of restricted expenditure from unrestricted reserve - Total including non-controlling interest,
SOCE - Balance at end of the current year - Share capital,
SOCE - Balance at end of the current year - Revenue reserve Restricted fund,SOCE - Balance at end of the current year - Revenue reserve Unrestricted fund,
SOCE - Balance at end of the current year - Restricted reserve,
SOCE - Balance at end of the current year - Revaluation reserve,
SOCE - Balance at end of the current year - Total excluding non-controlling interest,
SOCE - Balance at end of the current year - Non-controlling interest,
SOCE - Balance at end of the current year - Total including non-controlling interest,
SOFP - Intangible assets and goodwill,
SOFP - Housing properties-NBV,
SOFP - Negative goodwill,
SOFP - Net housing assets,
SOFP - Non-current investments,
SOFP - Other plant property and equipment,
SOFP - Investments in joint ventures and associates,
SOFP - Total non-current assets,
SOFP - Receivables due after more than one year,
SOFP - Investments,
SOFP - Stock and work in progress,
SOFP - Trade and other receivables due within one year,
SOFP - Cash and cash equivalents,
SOFP - Total current assets,
SOFP - Payables due within one year,
SOFP - Scottish housing grants due within one year,
SOFP - Other grants due within one year,
SOFP - Total deferred income due within one year,
SOFP - Net current assets/(liabilities),
SOFP - Total assets less current liabilities,
SOFP - Payables due after more than one year,
SOFP - Provisions,
SOFP - Pension asset/(liability),
SOFP - Scottish housing grants due after more than one year,
SOFP - Other grants due after more than one year,
SOFP - Total deferred income due after more than one year,
SOFP - Total long term liabilities,
SOFP - Net assets,
SOFP - Share capital,
SOFP - Revaluation reserves,
SOFP - Restricted reserves,
SOFP - Revenue reserves,
SOFP - Total reserves,
SOCF - Net cash inflow/(outflow) from operating activities,
SOCF - Tax (paid)/refunded,
SOCF - Acquisition and construction of properties,
SOCF - Purchase of other non-current assets,
SOCF - Sales of properties,
SOCF - Sales of other non-current assets,
SOCF - Capital Grants received,
SOCF - Capital Grants repaid,
SOCF - Interest received,
SOCF - Net cash inflow/(outflow) from investing activities,
SOCF - Interest paid,
SOCF - Interest element of finance lease rental payment,
SOCF - Share capital received/(repaid),
SOCF - Funding drawn down,
SOCF - Funding repaid,
SOCF - Early repayment and associated charges,
SOCF - Capital element of finance lease rental payments,
SOCF - Withdrawal from deposits,
SOCF - Net cash inflow/(outflow) from financing,
SOCF - Net change in cash and cash equivalents,
SOCF - Cash and cash equivalents at end of the previous year,
SOCF - Cash and cash equivalents Opening balance adjustments,
SOCF - Cash and cash equivalents at end of the current year,


Affordable Lettings - Rent receivable - General Needs Social Housing,
Affordable Lettings - Rent receivable - Supported Social Housing Accommodation,
Affordable Lettings - Rent receivable - Shared Ownership Housing,
Affordable Lettings - Rent receivable - Other,
Affordable Lettings - Rent receivable - Total,
Affordable Lettings - Service charges - General Needs Social Housing,
Affordable Lettings - Service charges - Supported Social Housing Accommodation,
Affordable Lettings - Service charges - Shared Ownership Housing,
Affordable Lettings - Service charges - Other,
Affordable Lettings - Service charges - Total,
Affordable Lettings - Gross income - General Needs Social Housing,
Affordable Lettings - Gross income - Supported Social Housing Accommodation,
Affordable Lettings - Gross income - Shared Ownership Housing,
Affordable Lettings - Gross income - Other,
Affordable Lettings - Gross income - Total,
Affordable Lettings - Voids - General Needs Social Housing,
Affordable Lettings - Voids - Supported Social Housing Accommodation,
Affordable Lettings - Voids - Shared Ownership Housing,
Affordable Lettings - Voids - Other,
Affordable Lettings - Voids - Total,
Affordable Lettings - Net income - General Needs Social Housing,
Affordable Lettings - Net income - Supported Social Housing Accommodation,
Affordable Lettings - Net income - Shared Ownership Housing,
Affordable Lettings - Net income - Other,
Affordable Lettings - Net income - Total,
Affordable Lettings - Grants released from deferred income - General Needs Social Housing,
Affordable Lettings - Grants released from deferred income - Supported Social Housing Accommodation,
Affordable Lettings - Grants released from deferred income - Shared Ownership Housing,
Affordable Lettings - Grants released from deferred income - Other,
Affordable Lettings - Grants released from deferred income - Total,
Affordable Lettings - Revenue grants from Scottish Ministers - General Needs Social Housing,
Affordable Lettings - Revenue grants from Scottish Ministers - Supported Social Housing Accommodation,
Affordable Lettings - Revenue grants from Scottish Ministers - Shared Ownership Housing,
Affordable Lettings - Revenue grants from Scottish Ministers - Other,
Affordable Lettings - Revenue grants from Scottish Ministers - Total,
Affordable Lettings - Other revenue grants - General Needs Social Housing,
Affordable Lettings - Other revenue grants - Supported Social Housing Accommodation,
Affordable Lettings - Other revenue grants - Shared Ownership Housing,
Affordable Lettings - Other revenue grants - Other,
Affordable Lettings - Other revenue grants - Total,
Affordable Lettings - Total turnover: letting - General Needs Social Housing,
Affordable Lettings - Total turnover: letting - Supported Social Housing Accommodation,
Affordable Lettings - Total turnover: letting - Shared Ownership Housing,
Affordable Lettings - Total turnover: letting - Other,
Affordable Lettings - Total turnover: letting - Total,
Affordable Lettings - Management and maintenance administration costs - General Needs Social Housing,
Affordable Lettings - Management and maintenance administration costs - Supported Social Housing Accommodation,
Affordable Lettings - Management and maintenance administration costs - Shared Ownership Housing,
Affordable Lettings - Management and maintenance administration costs - Other,
Affordable Lettings - Management and maintenance administration costs - Total,
Affordable Lettings - Service costs - General Needs Social Housing,
Affordable Lettings - Service costs - Supported Social Housing Accommodation,
Affordable Lettings - Service costs - Shared Ownership Housing,
Affordable Lettings - Service costs - Other,
Affordable Lettings - Service costs - Total,
Affordable Lettings - Planned maintenance - General Needs Social Housing,
Affordable Lettings - Planned maintenance - Supported Social Housing Accommodation,
Affordable Lettings - Planned maintenance - Shared Ownership Housing,
Affordable Lettings - Planned maintenance - Other,
Affordable Lettings - Planned maintenance - Total,
Affordable Lettings - Reactive maintenance - General Needs Social Housing,
Affordable Lettings - Reactive maintenance - Supported Social Housing Accommodation,
Affordable Lettings - Reactive maintenance - Shared Ownership Housing,
Affordable Lettings - Reactive maintenance - Other,
Affordable Lettings - Reactive maintenance - Total,
Affordable Lettings - Bad debts written (off)/back - General Needs Social Housing,
Affordable Lettings - Bad debts written (off)/back - Supported Social Housing Accommodation,
Affordable Lettings - Bad debts written (off)/back - Shared Ownership Housing,
Affordable Lettings - Bad debts written (off)/back - Other,
Affordable Lettings - Bad debts written (off)/back - Total,
Affordable Lettings - Depreciation: housing - General Needs Social Housing,
Affordable Lettings - Depreciation: housing - Supported Social Housing Accommodation,
Affordable Lettings - Depreciation: housing - Shared Ownership Housing,
Affordable Lettings - Depreciation: housing - Other,
Affordable Lettings - Depreciation: housing - Total,
Affordable Lettings - Impairment - General Needs Social Housing,
Affordable Lettings - Impairment - Supported Social Housing Accommodation,
Affordable Lettings - Impairment - Shared Ownership Housing,
Affordable Lettings - Impairment - Other,
Affordable Lettings - Impairment - Total,
Affordable Lettings - Operating costs - General Needs Social Housing,
Affordable Lettings - Operating costs - Supported Social Housing Accommodation,
Affordable Lettings - Operating costs - Shared Ownership Housing,
Affordable Lettings - Operating costs - Other,
Affordable Lettings - Operating costs - Total,
Affordable Lettings - Operating surplus/(deficit) - General Needs Social Housing,
Affordable Lettings - Operating surplus/(deficit) - Supported Social Housing Accommodation,
Affordable Lettings - Operating surplus/(deficit) - Shared Ownership Housing,
Affordable Lettings - Operating surplus/(deficit) - Other,
Affordable Lettings - Operating surplus/(deficit) - Total,
Other Activities - Wider role - Grants from Scottish Ministers,
Other Activities - Wider role - Other revenue grants,
Other Activities - Wider role - Supporting people income,
Other Activities - Wider role - Other income,
Other Activities - Wider role - Total turnover,
Other Activities - Wider role - Other operating costs,
Other Activities - Wider role - Operating surplus/(deficit),
Other Activities - Care and repair - Grants from Scottish Ministers,
Other Activities - Care and repair - Other revenue grants,
Other Activities - Care and repair - Supporting people income,
Other Activities - Care and repair - Other income,
Other Activities - Care and repair - Total turnover,
Other Activities - Care and repair - Other operating costs,
Other Activities - Care and repair - Operating surplus/(deficit),
Other Activities - Investment property activities - Grants from Scottish Ministers,
Other Activities - Investment property activities - Other revenue grants,
Other Activities - Investment property activities - Supporting people income,
Other Activities - Investment property activities - Other income,
Other Activities - Investment property activities - Total turnover,
Other Activities - Investment property activities - Other operating costs,
Other Activities - Investment property activities - Operating surplus/(deficit),
Other Activities - Factoring - Grants from Scottish Ministers,
Other Activities - Factoring - Other revenue grants,
Other Activities - Factoring - Supporting people income,
Other Activities - Factoring - Other income,
Other Activities - Factoring - Total turnover,
Other Activities - Factoring - Other operating costs,
Other Activities - Factoring - Operating surplus/(deficit),
Other Activities - Support activities - Grants from Scottish Ministers,
Other Activities - Support activities - Other revenue grants,
Other Activities - Support activities - Supporting people income,
Other Activities - Support activities - Other income,
Other Activities - Support activities - Total turnover,
Other Activities - Support activities - Other operating costs,
Other Activities - Support activities - Operating surplus/(deficit),
Other Activities - Care activities - Grants from Scottish Ministers,
Other Activities - Care activities - Other revenue grants,
Other Activities - Care activities - Supporting people income,
Other Activities - Care activities - Other income,
Other Activities - Care activities - Total turnover,
Other Activities - Care activities - Other operating costs,
Other Activities - Care activities - Operating surplus/(deficit),
Other Activities - Contracted out services undertaken for RSLs - Grants from Scottish Ministers,
Other Activities - Contracted out services undertaken for RSLs - Other revenue grants,
Other Activities - Contracted out services undertaken for RSLs - Supporting people income,
Other Activities - Contracted out services undertaken for RSLs - Other income,
Other Activities - Contracted out services undertaken for RSLs - Total turnover,
Other Activities - Contracted out services undertaken for RSLs - Other operating costs,
Other Activities - Contracted out services undertaken for RSLs - Operating surplus/(deficit),
Other Activities - Contracted out services undertaken for others - Grants from Scottish Ministers,
Other Activities - Contracted out services undertaken for others - Other revenue grants,
Other Activities - Contracted out services undertaken for others - Supporting people income,
Other Activities - Contracted out services undertaken for others - Other income,
Other Activities - Contracted out services undertaken for others - Total turnover,
Other Activities - Contracted out services undertaken for others - Other operating costs,
Other Activities - Contracted out services undertaken for others - Operating surplus/(deficit),
Other Activities - Developments for sale to RSLs - Grants from Scottish Ministers,
Other Activities - Developments for sale to RSLs - Other revenue grants,
Other Activities - Developments for sale to RSLs - Supporting people income,
Other Activities - Developments for sale to RSLs - Other income,
Other Activities - Developments for sale to RSLs - Total turnover,
Other Activities - Developments for sale to RSLs - Other operating costs,
Other Activities - Developments for sale to RSLs - Operating surplus/(deficit),
Other Activities - Developments for sale to non-RSLs - Grants from Scottish Ministers,
Other Activities - Developments for sale to non-RSLs - Other revenue grants,
Other Activities - Developments for sale to non-RSLs - Supporting people income,
Other Activities - Developments for sale to non-RSLs - Other income,
Other Activities - Developments for sale to non-RSLs - Total turnover,
Other Activities - Developments for sale to non-RSLs - Other operating costs,
Other Activities - Developments for sale to non-RSLs - Operating surplus/(deficit),
Other Activities - Uncapitalised development administration costs - Grants from Scottish Ministers,
Other Activities - Uncapitalised development administration costs - Other revenue grants,
Other Activities - Uncapitalised development administration costs - Supporting people income,
Other Activities - Uncapitalised development administration costs - Other income,
Other Activities - Uncapitalised development administration costs - Total turnover,
Other Activities - Uncapitalised development administration costs - Other operating costs,
Other Activities - Uncapitalised development administration costs - Operating surplus/(deficit),
Other Activities - 
Other activities - Grants from Scottish Ministers,
Other Activities - 
Other activities - Other revenue grants,
Other Activities - 
Other activities - Supporting people income,
Other Activities - 
Other activities - Other income,
Other Activities - 
Other activities - Total turnover,
Other Activities - 
Other activities - Other operating costs,
Other Activities - 
Other activities - Operating surplus/(deficit),
Other Activities - Total - Grants from Scottish Ministers,
Other Activities - Total - Other revenue grants,
Other Activities - Total - Supporting people income,
Other Activities - Total - Other income,
Other Activities - Total - Total turnover,
Other Activities - Total - Other operating costs,
Other Activities - Total - Operating surplus/(deficit),
Analysis Units - Units owned and managed at year end - General Needs Social Housing,
Analysis Units - Units owned and managed at year end - Supported Social Housing Accommodation,
Analysis Units - Units owned and managed at year end - Shared Ownership Housing,
Analysis Units - Units owned and managed at year end - Other,
Analysis Units - Units owned and managed at year end - Total,
Analysis Units - Units managed not owned at year end - General Needs Social Housing,
Analysis Units - Units managed not owned at year end - Supported Social Housing Accommodation,
Analysis Units - Units managed not owned at year end - Shared Ownership Housing,
Analysis Units - Units managed not owned at year end - Other,
Analysis Units - Units managed not owned at year end - Total,
Analysis Units - Units owned not managed at year end - General Needs Social Housing,
Analysis Units - Units owned not managed at year end - Supported Social Housing Accommodation,
Analysis Units - Units owned not managed at year end - Shared Ownership Housing,
Analysis Units - Units owned not managed at year end - Other,
Analysis Units - Units owned not managed at year end - Total,
Analysis Units - Units held for demolition at year end - General Needs Social Housing,
Analysis Units - Units held for demolition at year end - Supported Social Housing Accommodation,
Analysis Units - Units held for demolition at year end - Shared Ownership Housing,
Analysis Units - Units held for demolition at year end - Other,
Analysis Units - Units held for demolition at year end - Total,
Analysis Units - Total units owned / managed - General Needs Social Housing,
Analysis Units - Total units owned / managed - Supported Social Housing Accommodation,
Analysis Units - Total units owned / managed - Shared Ownership Housing,
Analysis Units - Total units owned / managed - Other,
Analysis Units - Total units owned / managed - Total,
Supplementary Items - Chief executive emoluments excluding pension contribution,
Supplementary Items - Total key management personnel emoluments,
Supplementary Items - Total staff costs,
Supplementary Items - External auditors' fees - audit,
Supplementary Items - External auditors' fees - other,
Supplementary Items - Capitalised maintenance costs,
Supplementary Items - Capitalised development administration costs,
Supplementary Items - Capitalised interest costs,
Supplementary Items - Accumulated depreciation,
Supplementary Items - Receivables - gross rental,
Supplementary Items - Receivables - bad debt provision,
Supplementary Items - Receivables - net rental,
Supplementary Items - Pension deficit recovery payments due within one year,
Supplementary Items - Pension deficit recovery payments due after more than one year,
Supplementary Items - Total Pension deficit recovery payments due,
Supplementary Items - Housing loans due within one year,
Supplementary Items - Housing loans due after more than one year,
Supplementary Items - Other loans due within one year,
Supplementary Items - Other loans due after more than one year,
Supplementary Items - Overdraft / bridging finance,
Supplementary Items - Intra-group loans due within one year,
Supplementary Items - Intra-group loans due after more than one year,
Supplementary Items - Intra-group lending,
Supplementary Items - Intra-group receivables (trading),
Supplementary Items - Other intra-group payables (trading),
Contextual Information - Accounting year end,
Contextual Information - Date financial statements authorised,
Contextual Information - Financial statements qualified indicator,
Contextual Information - Emphasis of matter points raised indicator,
Contextual Information - External auditors' name,
Contextual Information - Internal auditors' name,
Contextual Information - Audit Committee indicator,
Contextual Information - Housing assets revaluation indicator,
Contextual Information - Capital grant income indicator,
Contextual Information - Calendar year of last housing assets revaluation,
Contextual Information - Contingent liabilities - Legal action,
Contextual Information - Contingent liabilities - LSVT contract compliance,
Contextual Information - Contingent liabilities - Pension,
Contextual Information - Contingent liabilities - Repayment of SHG,
Contextual Information - Contingent liabilities - Other,
Contextual Information - Contingent liabilities - None,
Contextual Information - Staff members not contributing to any pension scheme,
Contextual Information - Staff Pension Scheme Row 1,
Contextual Information - Participating members Row 1,
Contextual Information - Staff Pension Scheme Row 2,
Contextual Information - Participating members Row 2,
Contextual Information - Staff Pension Scheme Row 3,
Contextual Information - Participating members Row 3,
Contextual Information - Staff Pension Scheme Row 4,
Contextual Information - Participating members Row 4,
Contextual Information - Staff Pension Scheme Row 5,
Contextual Information - Participating members Row 5,
Contextual Information - Staff Pension Scheme Row 6,
Contextual Information - Participating members Row 6,
Contextual Information - Staff Pension Scheme Row 7,
Contextual Information - Participating members Row 7,
Contextual Information - Staff Pension Scheme Row 8,
Contextual Information - Participating members Row 8,
Costs per Unit - Management and maintenance administration - General Needs Social Housing,
Costs per Unit - Management and maintenance administration - Supported Social Housing Accommodation,
Costs per Unit - Management and maintenance administration - Shared Ownership Housing,
Costs per Unit - Management and maintenance administration - Other,
Costs per Unit - Management and maintenance administration - Total,
Costs per Unit - Planned maintenance - General Needs Social Housing,
Costs per Unit - Planned maintenance - Supported Social Housing Accommodation,
Costs per Unit - Planned maintenance - Shared Ownership Housing,
Costs per Unit - Planned maintenance - Other,
Costs per Unit - Planned maintenance - Total,
Costs per Unit - Reactive maintenance - General Needs Social Housing,
Costs per Unit - Reactive maintenance - Supported Social Housing Accommodation,
Costs per Unit - Reactive maintenance - Shared Ownership Housing,
Costs per Unit - Reactive maintenance - Other,
Costs per Unit - Reactive maintenance - Total,
Costs per Unit - Total direct maintenance - General Needs Social Housing,
Costs per Unit - Total direct maintenance - Supported Social Housing Accommodation,
Costs per Unit - Total direct maintenance - Shared Ownership Housing,
Costs per Unit - Total direct maintenance - Other,
Costs per Unit - Total direct maintenance - Total,
Costs per Unit - Total management and maintenance - General Needs Social Housing,
Costs per Unit - Total management and maintenance - Supported Social Housing Accommodation,
Costs per Unit - Total management and maintenance - Shared Ownership Housing,
Costs per Unit - Total management and maintenance - Other,
Costs per Unit - Total management and maintenance - Total,
Ratios - Interest cover (%),
Ratios - Gearing (%),
Ratios - Voids (%),
Ratios - Gross arrears (%),
Ratios - Net arrears (%),
Ratios - Bad debts (%),
Ratios - Staff costs / turnover (%),
Ratios - Key management personnel / staff costs (%),
Ratios - Turnover per unit (�),
Ratios - Responsive repairs to planned maintenance,
Ratios - Current ratio,
Ratios - Gross surplus / (deficit) (%),
Ratios - Net surplus / (deficit) (%),
Ratios - EBITDA / revenue (%),
Ratios - EBITDA exc. deferred grant (%),
Ratios - Debt burden,
Ratios - Net debt per unit (�),
Ratios - Debt per unit (�),
Ratios - Income from non-rental activities (%)

'''